#!/usr/bin/env bash
# tools/stack.sh — bring the local stack up, tear it down, follow its logs.
# Run by `just stack-init`, `just up`, `just down`, `just logs`.
#
# Orchestration only: process lifecycle and health polling, which is what shell
# is for. The end-to-end assertion is `just stack-check`, and it lives in
# tools/stack_probe.py because it is JSON construction and parsing — see
# `just lint`, which fails if an interpreter is ever embedded in a shell script
# again.
#
# `up` refuses to report success before the stack is actually serving. A `just
# up` that returns 0 while nothing works would be this repo's own thesis,
# self-inflicted.
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
cd "$(repo_root)"

GATE="stack"
ENV_FILE=".env"

# podman cannot bind-mount every filesystem — on macOS it sees the home volume
# and not an external one. Detected rather than assumed; see docs/06-stack.md.
compose() {
  if command -v podman >/dev/null 2>&1; then
    podman compose "$@"
  elif command -v docker >/dev/null 2>&1; then
    docker compose "$@"
  else
    die "$GATE" "neither podman nor docker found — install one and re-run"
  fi
}

# wait_http <name> <url> <seconds>
wait_http() {
  local name=$1 url=$2 budget=$3 waited=0
  while [ "$waited" -lt "$budget" ]; do
    if curl -fsS --max-time 2 "$url" >/dev/null 2>&1; then
      ok "$GATE" "$name is serving"
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
  done
  fail "$GATE" "$name did not become ready within ${budget}s ($url)"
  return 1
}

cmd_init() {
  if [ -f "$ENV_FILE" ] && grep -q '^OTEL_GATEWAY_TOKEN=' "$ENV_FILE"; then
    ok "$GATE" "$ENV_FILE already has a token — leaving it alone"
    return 0
  fi
  # Local-only credential. Real tokens must never land here: `just leaks`
  # scans this file precisely because it is where one would end up.
  local token
  token="dev-$(head -c 18 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)"
  {
    echo "# Generated by \`just stack-init\`. Local development only."
    echo "# Gitignored. Do not put a real token here."
    echo "OTEL_GATEWAY_TOKEN=$token"
  } >"$ENV_FILE"
  ok "$GATE" "wrote $ENV_FILE with a local dev token"
}

cmd_up() {
  [ -f "$ENV_FILE" ] || die "$GATE" "no $ENV_FILE — run \`just stack-init\` first"

  compose up -d
  echo

  local failed=0
  wait_http "collector-agent" "http://127.0.0.1:13133/ready" 60 || failed=1
  wait_http "prometheus" "http://127.0.0.1:9090/-/ready" 60 || failed=1
  wait_http "loki" "http://127.0.0.1:3100/ready" 90 || failed=1
  wait_http "tempo" "http://127.0.0.1:3200/ready" 90 || failed=1
  wait_http "grafana" "http://127.0.0.1:3000/api/health" 90 || failed=1

  if [ "$failed" -ne 0 ]; then
    echo
    warn "$GATE" "one or more services did not come up — \`just logs\` for why"
    exit 1
  fi

  echo
  ok "$GATE" "stack is up — grafana on http://127.0.0.1:3000, then \`just stack-check\`"
}

cmd_down() {
  compose down "$@"
  ok "$GATE" "stack is down"
}

cmd_logs() {
  compose logs -f "$@"
}

case "${1:-}" in
  init) cmd_init ;;
  up) cmd_up ;;
  down)
    shift
    cmd_down "$@"
    ;;
  logs)
    shift
    cmd_logs "$@"
    ;;
  *) die "$GATE" "usage: stack.sh {init|up|down|logs}" ;;
esac
